"""Add LLM settings to Quiz model

Revision ID: 0c20b0b588cf
Revises: 2f157f577824
Create Date: 2025-06-24 09:43:11.089842

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0c20b0b588cf'
down_revision = '2f157f577824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('question_count', sa.Integer(), nullable=False))
    op.add_column('quiz', sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('quiz', sa.Column('llm_temperature', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'llm_temperature')
    op.drop_column('quiz', 'llm_model')
    op.drop_column('quiz', 'question_count')
    # ### end Alembic commands ###
