"""Add canvas export tracking fields to Quiz and Question models

Revision ID: 1c75f546f2b3
Revises: c79b13dadeef
Create Date: 2025-06-27 10:37:07.992921

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1c75f546f2b3'
down_revision = 'c79b13dadeef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('canvas_item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quiz', sa.Column('canvas_quiz_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quiz', sa.Column('export_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('quiz', sa.Column('exported_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'exported_at')
    op.drop_column('quiz', 'export_status')
    op.drop_column('quiz', 'canvas_quiz_id')
    op.drop_column('question', 'canvas_item_id')
    # ### end Alembic commands ###
