// This file is auto-generated by @hey-api/openapi-ts

export type CanvasCourse = {
  id: number
  name: string
}

export type CanvasModule = {
  id: number
  name: string
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type Message = {
  message: string
}

export type QuestionPublic = {
  id: string
  quiz_id: string
  question_text: string
  option_a: string
  option_b: string
  option_c: string
  option_d: string
  correct_answer: string
  is_approved: boolean
  approved_at: string | null
  created_at: string | null
  updated_at: string | null
  canvas_item_id: string | null
}

export type QuestionUpdate = {
  question_text?: string | null
  option_a?: string | null
  option_b?: string | null
  option_c?: string | null
  option_d?: string | null
  /**
   * Must be A, B, C, or D
   */
  correct_answer?: string | null
}

export type Quiz = {
  id?: string
  owner_id: string
  canvas_course_id: number
  canvas_course_name: string
  selected_modules?: {
    [key: string]: string
  }
  title: string
  question_count?: number
  llm_model?: string
  llm_temperature?: number
  /**
   * Status of content extraction: pending, processing, completed, failed
   */
  content_extraction_status?: string
  /**
   * Status of LLM generation: pending, processing, completed, failed
   */
  llm_generation_status?: string
  extracted_content?: {
    [key: string]: unknown
  } | null
  /**
   * Timestamp when content extraction was completed
   */
  content_extracted_at?: string | null
  created_at?: string | null
  updated_at?: string | null
  /**
   * Canvas quiz assignment ID after export
   */
  canvas_quiz_id?: string | null
  /**
   * Status of Canvas export: pending, processing, completed, failed
   */
  export_status?: string
  /**
   * Timestamp when quiz was exported to Canvas
   */
  exported_at?: string | null
}

export type QuizCreate = {
  canvas_course_id: number
  canvas_course_name: string
  selected_modules: {
    [key: string]: string
  }
  title: string
  question_count?: number
  llm_model?: string
  llm_temperature?: number
}

export type UserPublic = {
  name: string
  onboarding_completed: boolean
}

export type UserUpdateMe = {
  name: string
  onboarding_completed?: boolean | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type AuthLoginCanvasResponse = unknown

export type AuthAuthCanvasResponse = unknown

export type AuthLogoutCanvasResponse = {
  [key: string]: string
}

export type AuthRefreshCanvasTokenResponse = {
  [key: string]: string
}

export type CanvasGetCoursesResponse = Array<CanvasCourse>

export type CanvasGetCourseModulesData = {
  courseId: number
}

export type CanvasGetCourseModulesResponse = Array<CanvasModule>

export type CanvasGetModuleItemsData = {
  courseId: number
  moduleId: number
}

export type CanvasGetModuleItemsResponse = Array<{
  [key: string]: unknown
}>

export type CanvasGetPageContentData = {
  courseId: number
  pageUrl: string
}

export type CanvasGetPageContentResponse = {
  [key: string]: unknown
}

export type CanvasGetFileInfoData = {
  courseId: number
  fileId: number
}

export type CanvasGetFileInfoResponse = {
  [key: string]: unknown
}

export type QuestionsGetQuizQuestionsData = {
  quizId: string
}

export type QuestionsGetQuizQuestionsResponse = Array<QuestionPublic>

export type QuestionsGetQuestionData = {
  questionId: string
  quizId: string
}

export type QuestionsGetQuestionResponse = QuestionPublic

export type QuestionsUpdateQuizQuestionData = {
  questionId: string
  quizId: string
  requestBody: QuestionUpdate
}

export type QuestionsUpdateQuizQuestionResponse = QuestionPublic

export type QuestionsDeleteQuizQuestionData = {
  questionId: string
  quizId: string
}

export type QuestionsDeleteQuizQuestionResponse = Message

export type QuestionsApproveQuizQuestionData = {
  questionId: string
  quizId: string
}

export type QuestionsApproveQuizQuestionResponse = QuestionPublic

export type QuizGetUserQuizzesEndpointResponse = Array<Quiz>

export type QuizCreateNewQuizData = {
  requestBody: QuizCreate
}

export type QuizCreateNewQuizResponse = Quiz

export type QuizGetQuizData = {
  quizId: string
}

export type QuizGetQuizResponse = Quiz

export type QuizDeleteQuizEndpointData = {
  quizId: string
}

export type QuizDeleteQuizEndpointResponse = Message

export type QuizTriggerContentExtractionData = {
  quizId: string
}

export type QuizTriggerContentExtractionResponse = {
  [key: string]: string
}

export type QuizTriggerQuestionGenerationData = {
  quizId: string
}

export type QuizTriggerQuestionGenerationResponse = {
  [key: string]: string
}

export type QuizGetQuizQuestionStatsData = {
  quizId: string
}

export type QuizGetQuizQuestionStatsResponse = {
  [key: string]: number
}

export type QuizExportQuizToCanvasData = {
  quizId: string
}

export type QuizExportQuizToCanvasResponse = {
  [key: string]: string
}

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UtilsHealthCheckResponse = boolean

export type UtilsGetDbHealthResponse = {
  [key: string]: unknown
}
