// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  AuthLoginCanvasResponse,
  AuthAuthCanvasResponse,
  AuthLogoutCanvasResponse,
  AuthRefreshCanvasTokenResponse,
  UsersReadUserMeResponse,
  UsersDeleteUserMeResponse,
  UsersUpdateUserMeData,
  UsersUpdateUserMeResponse,
  UtilsHealthCheckResponse,
} from "./types.gen"

export class AuthService {
  /**
   * Login Canvas
   * Generate Canvas OAuth2 authorization URL and redirect
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static loginCanvas(): CancelablePromise<AuthLoginCanvasResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/auth/login/canvas",
    })
  }

  /**
   * Auth Canvas
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static authCanvas(): CancelablePromise<AuthAuthCanvasResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/auth/callback/canvas",
    })
  }

  /**
   * Logout Canvas
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static logoutCanvas(): CancelablePromise<AuthLogoutCanvasResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/auth/logout",
    })
  }

  /**
   * Refresh Canvas Token
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static refreshCanvasToken(): CancelablePromise<AuthRefreshCanvasTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/auth/refresh",
    })
  }
}

export class UsersService {
  /**
   * Read User Me
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Delete User Me
   * Delete own user.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Update User Me
   * Update own user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUserMe(
    data: UsersUpdateUserMeData,
  ): CancelablePromise<UsersUpdateUserMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UtilsService {
  /**
   * Health Check
   * @returns boolean Successful Response
   * @throws ApiError
   */
  public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/health-check/",
    })
  }
}
