// This file is auto-generated by @hey-api/openapi-ts

export type CanvasCourse = {
  id: number
  name: string
}

export type CanvasModule = {
  id: number
  name: string
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type Message = {
  message: string
}

export type Quiz = {
  id?: string
  owner_id: string
  canvas_course_id: number
  canvas_course_name: string
  /**
   * JSON array of selected Canvas modules
   */
  selected_modules: string
  title: string
  question_count?: number
  llm_model?: string
  llm_temperature?: number
  created_at?: string | null
  updated_at?: string | null
}

export type QuizCreate = {
  canvas_course_id: number
  canvas_course_name: string
  selected_modules: {
    [key: string]: string
  }
  title: string
  question_count?: number
  llm_model?: string
  llm_temperature?: number
}

export type UserPublic = {
  name: string
  onboarding_completed: boolean
}

export type UserUpdateMe = {
  name: string
  onboarding_completed?: boolean | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type AuthLoginCanvasResponse = unknown

export type AuthAuthCanvasResponse = unknown

export type AuthLogoutCanvasResponse = {
  [key: string]: string
}

export type AuthRefreshCanvasTokenResponse = {
  [key: string]: string
}

export type CanvasGetCoursesResponse = Array<CanvasCourse>

export type CanvasGetCourseModulesData = {
  courseId: number
}

export type CanvasGetCourseModulesResponse = Array<CanvasModule>

export type QuizGetUserQuizzesEndpointResponse = Array<Quiz>

export type QuizCreateNewQuizData = {
  requestBody: QuizCreate
}

export type QuizCreateNewQuizResponse = Quiz

export type QuizGetQuizData = {
  quizId: string
}

export type QuizGetQuizResponse = Quiz

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UtilsHealthCheckResponse = boolean
