"""Add content extraction fields to quiz model

Revision ID: 279918ad3a1e
Revises: 387a734aea0f
Create Date: 2025-06-24 12:55:31.728509

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '279918ad3a1e'
down_revision = '387a734aea0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('content_extraction_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('quiz', sa.Column('llm_generation_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('quiz', sa.Column('extracted_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quiz', sa.Column('content_extracted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'content_extracted_at')
    op.drop_column('quiz', 'extracted_content')
    op.drop_column('quiz', 'llm_generation_status')
    op.drop_column('quiz', 'content_extraction_status')
    # ### end Alembic commands ###
