"""Update_at field is not null on creation

Revision ID: 387a734aea0f
Revises: 0c20b0b588cf
Create Date: 2025-06-24 10:23:36.321504

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '387a734aea0f'
down_revision = '0c20b0b588cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
