"""Add RAGAS validation metadata to Question

Revision ID: 7e55977e78f8
Revises: a051a87cf73b
Create Date: 2025-07-21 12:57:10.165773

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e55977e78f8'
down_revision = 'a051a87cf73b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('validation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'validation_metadata')
    # ### end Alembic commands ###
