"""add edit_log field to question model

Revision ID: a9f521ff0dee
Revises: d4ab7062b1ab
Create Date: 2025-08-05 08:59:31.047350

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9f521ff0dee'
down_revision = 'd4ab7062b1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('edit_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'edit_log')
    # ### end Alembic commands ###
