"""add tone field to Quiz model

Revision ID: d4ab7062b1ab
Revises: a8587fe4d2d3
Create Date: 2025-07-31 09:04:30.476574

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd4ab7062b1ab'
down_revision = 'a8587fe4d2d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('tone', sa.Enum('ACADEMIC', 'CASUAL', 'ENCOURAGING', 'PROFESSIONAL', name='quiztone'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'tone')
    # ### end Alembic commands ###
