"""add tone field to Quiz model

Revision ID: d4ab7062b1ab
Revises: a8587fe4d2d3
Create Date: 2025-07-31 09:04:30.476574

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd4ab7062b1ab'
down_revision = 'a8587fe4d2d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    quiztone_enum = sa.Enum('ACADEMIC', 'CASUAL', 'ENCOURAGING', 'PROFESSIONAL', name='quiztone')
    quiztone_enum.create(op.get_bind(), checkfirst=True)
    # Step 1: Add as nullable
    op.add_column('quiz', sa.Column('tone', quiztone_enum, nullable=True))
    # Step 2: Populate existing rows with default value
    op.execute("UPDATE quiz SET tone='ACADEMIC' WHERE tone IS NULL")
    # Step 3: Alter to NOT NULL
    op.alter_column('quiz', 'tone', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'tone')
    quiztone_enum = sa.Enum('ACADEMIC', 'CASUAL', 'ENCOURAGING', 'PROFESSIONAL', name='quiztone')
    quiztone_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
