"""add missing indexes for foreign keys and status fields

Revision ID: 00ce39f73e5b
Revises: 78d09a4cb335
Create Date: 2025-06-29 16:57:56.507559

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '00ce39f73e5b'
down_revision = '78d09a4cb335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_question_is_approved'), 'question', ['is_approved'], unique=False)
    op.create_index(op.f('ix_question_quiz_id'), 'question', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_content_extraction_status'), 'quiz', ['content_extraction_status'], unique=False)
    op.create_index(op.f('ix_quiz_export_status'), 'quiz', ['export_status'], unique=False)
    op.create_index(op.f('ix_quiz_llm_generation_status'), 'quiz', ['llm_generation_status'], unique=False)
    op.create_index(op.f('ix_quiz_owner_id'), 'quiz', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_owner_id'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_llm_generation_status'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_export_status'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_content_extraction_status'), table_name='quiz')
    op.drop_index(op.f('ix_question_quiz_id'), table_name='question')
    op.drop_index(op.f('ix_question_is_approved'), table_name='question')
    # ### end Alembic commands ###
