"""Added Quiz model

Revision ID: 2f157f577824
Revises: beaa03897078
Create Date: 2025-06-23 09:37:50.772186

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2f157f577824'
down_revision = 'beaa03897078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('canvas_course_id', sa.Integer(), nullable=False),
    sa.Column('canvas_course_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_modules', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_canvas_course_id'), 'quiz', ['canvas_course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_canvas_course_id'), table_name='quiz')
    op.drop_table('quiz')
    # ### end Alembic commands ###
