"""Convert JSON string columns to JSONB

Revision ID: 6da95a79f8d8
Revises: 00ce39f73e5b
Create Date: 2025-06-29 22:23:59.087863

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6da95a79f8d8'
down_revision = '00ce39f73e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz', 'selected_modules',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using='selected_modules::jsonb')
    op.alter_column('quiz', 'extracted_content',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='extracted_content::jsonb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz', 'extracted_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='extracted_content::text')
    op.alter_column('quiz', 'selected_modules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='selected_modules::text')
    # ### end Alembic commands ###
