"""Initial schema

Revision ID: 80188661b4b8
Revises:
Create Date: 2025-06-19 14:26:20.962049

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '80188661b4b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
