"""Add onboarding_completed field to User model

Revision ID: beaa03897078
Revises: f19ecfe187cf
Create Date: 2025-06-21 11:52:59.253249

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'beaa03897078'
down_revision = 'f19ecfe187cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('onboarding_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'onboarding_completed')
    # ### end Alembic commands ###
