"""Add Question model

Revision ID: c79b13dadeef
Revises: 279918ad3a1e
Create Date: 2025-06-25 11:41:41.219630

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c79b13dadeef'
down_revision = '279918ad3a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('option_a', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('option_b', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('option_c', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('option_d', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
